/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pc' at '17-5-10 下午12:15' with Gradle 2.14
 *
 * @author pc, @date 17-5-10 下午12:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
